(function(root){
  "use strict";
  const TIME_ZONE=(Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Chicago");
  function stationParts(date){const parts=new Intl.DateTimeFormat("en-US",{timeZone:TIME_ZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date);return Object.fromEntries(parts.filter(p=>p.type!=="literal").map(p=>[p.type,Number(p.value)]))}
  function zonedToUtc(year,month,day,hour=0,minute=0,second=0){const target=Date.UTC(year,month-1,day,hour,minute,second);let guess=target;for(let i=0;i<4;i++){const p=stationParts(new Date(guess)),represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);guess+=target-represented}return guess}
  function dateKey(nowMs){const p=stationParts(new Date(nowMs));return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`}
  function dayNumber(nowMs){const p=stationParts(new Date(nowMs));return Math.floor(Date.UTC(p.year,p.month-1,p.day)/86400000)}
  function hash(text){let value=2166136261;for(let i=0;i<text.length;i++)value=Math.imul(value^text.charCodeAt(i),16777619);return value>>>0}
  function shuffle(items,seedText){const out=items.slice();let seed=hash(seedText);function random(){seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  function playablePrograms(programs,excluded){const blocked=excluded instanceof Set?excluded:new Set(excluded||[]),seen=new Set();return Object.values(programs||{}).filter(item=>{if(!item||!item.videoId||!item.cleared||item.disabled||blocked.has(item.videoId)||seen.has(item.videoId))return false;seen.add(item.videoId);return true})}
  function createDaySchedule(nowMs,programs,template,excludedVideoIds){const p=stationParts(new Date(nowMs)),midnightMs=zonedToUtc(p.year,p.month,p.day),key=dateKey(nowMs),list=playablePrograms(programs,excludedVideoIds);const placeholder={id:"PBS-CATALOG-REFILL",title:"PBS archive refill in progress",year:"",era:"PBS",collection:"A fresh verified program will replace this slot",runtimeSeconds:0,videoId:"",cleared:false};if(!list.length)return template.map((slot,index)=>({id:`${key}-${String(index).padStart(3,"0")}`,movie:placeholder,startsAtMs:midnightMs+slot.minute*60000,endsAtMs:midnightMs+(slot.minute+slot.duration)*60000,blockSeconds:slot.duration*60}));
    const fingerprint=list.map(item=>item.id||item.videoId).sort().join("|"),deck=shuffle(list,`pbs-fresh-deck-v4:${fingerprint}`),start=(dayNumber(nowMs)*template.length)%deck.length,used=new Set();
    return template.map((slot,index)=>{let program=null;for(let step=0;step<deck.length;step++){const candidate=deck[(start+index+step)%deck.length],id=candidate.id||candidate.videoId;if(!used.has(id)){program=candidate;used.add(id);break}}if(!program)program=placeholder;return{id:`${key}-${String(index).padStart(3,"0")}`,movie:program,startsAtMs:midnightMs+slot.minute*60000,endsAtMs:midnightMs+(slot.minute+slot.duration)*60000,blockSeconds:slot.duration*60}})}
  function createSegments(block){const runtime=Math.min(block.movie.runtimeSeconds||block.blockSeconds,block.blockSeconds),segments=[];if(block.movie.videoId&&block.movie.cleared)segments.push({kind:"program",title:block.movie.title,videoId:block.movie.videoId,watchUrl:block.movie.watchUrl||"",cleared:true,sourceStart:0,stationStart:0,duration:runtime});else segments.push({kind:"station",title:block.movie.title,videoId:"",watchUrl:block.movie.watchUrl||"",cleared:false,sourceStart:0,stationStart:0,duration:Math.min(Math.max(runtime,1),block.blockSeconds)});if(runtime<block.blockSeconds)segments.push({kind:"station",title:"PBS station break — next fresh program starts on schedule",videoId:"",watchUrl:"",cleared:true,sourceStart:0,stationStart:Math.max(runtime,1),duration:block.blockSeconds-Math.max(runtime,1)});return segments}
  function resolve(nowMs,schedule){let block=schedule.find(item=>nowMs>=item.startsAtMs&&nowMs<item.endsAtMs);if(!block)block=nowMs<schedule[0].startsAtMs?schedule[0]:schedule[schedule.length-1];const blockElapsed=Math.max(0,Math.min(block.blockSeconds-1,Math.floor((nowMs-block.startsAtMs)/1000))),segments=createSegments(block),segment=segments.find(item=>blockElapsed>=item.stationStart&&blockElapsed<item.stationStart+item.duration)||segments[segments.length-1],segmentElapsed=Math.max(0,blockElapsed-segment.stationStart);return{block,segment,segmentElapsed,blockElapsed,mediaSeconds:segment.sourceStart+segmentElapsed,segmentRemaining:Math.max(0,segment.duration-segmentElapsed),blockRemaining:Math.max(0,block.blockSeconds-blockElapsed)}}
  root.PBSEngine={TIME_ZONE,stationParts,zonedToUtc,dateKey,createDaySchedule,createSegments,resolve};
})(window);
